name: sanchu5b
description: プロバイダ＆モデル形式の天運三柱推命アプリ
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 5.0.7+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    # 日本語化するために0.18.1 を　0.18.0 にする必要あり(2023.6.11)
  intl: ^0.18.0
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_lints: ^2.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

